name: CMake-Cross-Platform-Test

on: [push]

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make g++

      - name: Run CMake and Make
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Upload build artifact (Linux)
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: build/

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CMake and Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Upload build artifact (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/

